name: Deploying WordPress Site
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: rtCamp/action-deploy-wordpress@v3
        env:
          # Add your environment variables here
          MY_ENV_VAR: ${{ secrets.TEXTBELT }}
